### ISSUE TITLE
[react-komposer-1.4.0 / meteor-1.3-beta.12] _reactKomposer.composeWithTracker is not a function

### ISSUE THREAD

**Issue by staskorz** [kadirahq/react-komposer#56]
I get the following browser console error after upgrading react-komposer from 1.3.3 to 1.4.0:

`Uncaught TypeError: (0 , _reactKomposer.composeWithTracker) is not a function`

Downgrading react-komposer to 1.3.3 resolves the issue.

Meteor version: 1.3-beta.12.
OS: Windows 7 SP1 64bit
Browsers: Chrome 49, Firefox 45 and IE9

**Comment by arunoda** [comment]
Updated a new version. Try it now.

**Comment by staskorz** [comment]
Now I get another error:

![image](https://cloud.githubusercontent.com/assets/1193752/13807677/0a987518-eb6b-11e5-887c-f410d12d5e1c.png)

**Comment by arunoda** [comment]
This works for me. Try installing npm modules from the beginning.

**Comment by staskorz** [comment]
Works for me too after

```
# rm /rf ./node_modules
# npm install

```

Many many thanks!

Wow, the power of opensource! - I've reported an issue and you've published a working release in just 7 minutes! Awesome!! And thanks again!

**Comment by lyquocnam** [comment]
@staskorz ya, @arunoda  work so hard, good to follow him with meteor :+1:

**Comment by arunoda** [comment]
Oka guys. Hope we can close this issue.
